ruby-environment: &ruby-environment
  MONGO_HOST: 127.0.0.1
  BUNDLE_JOBS: 3
  BUNDLE_RETRY: 3

bundle-install: &bundle-install
  name: Bundle Install
  command: bundle install

wait-for-mongo: &wait-for-mongo
  name: Wait for Mongo
  command: dockerize --wait tcp://127.0.0.1:27017

rspec: &rspec
  name: RSpec
  command: |
    bundle exec rspec \
      --format RspecJunitFormatter \
      --out test_results/rspec.xml \
      --format progress

test-results-path: &test-results-path
  path: test_results

version: 2
jobs:
  ruby-24-mongoid-5:
    working_directory: ~/mongoidal-ruby-24
    docker:
      - image: circleci/ruby:2.4
        environment: *ruby-environment
      - image: circleci/mongo:3.6.9
    steps:
      - checkout
      - run: *bundle-install
      - run: *wait-for-mongo
      - run: *rspec
      - store_test_results: *test-results-path

  ruby-25-mongoid-6:
    working_directory: ~/mongoidal-ruby-25
    docker:
      - image: circleci/ruby:2.5
        environment: *ruby-environment
      - image: circleci/mongo:4.2.0
    steps:
      - checkout
      - run: *bundle-install
      - run: *wait-for-mongo
      - run: *rspec
      - store_test_results: *test-results-path

workflows:
  version: 2
  build:
    jobs:
      - ruby-24-mongoid-5
      - ruby-25-mongoid-6
